const res = {
  data: [
    {
      id: 1,
      makgeolliId: 18,
      userId: 1,
      star: 3.5,
      comment: '맛이끝내줍니자아주',
      image: '',
      username: '김코딩',
      createAt: '2021/01/13',
      updateAt: '',
    },

    {
      id: 2,
      makgeolliId: 18,
      userId: 1,
      star: 1.5,
      comment: '맛이끝내줍니자아주테스트입니다',
      image: '',
      username: '이코테',
      createAt: '2021/02/02',
      updateAt: '',
    },
    {
      id: 3,
      makgeolliId: 1,
      userId: 2,
      star: 4.5,
      comment:
        '맛이끝내줍니자아주테스트입니다 테스트입니다 테스트입니다 더미테스트입니다',
      image: '',
      username: 'miler5391',
      createAt: '2021/07/13',
      updateAt: '',
    },
    {
      id: 4,
      makgeolliId: 3,
      userId: 4,
      star: 2,
      comment: '테스트용 댓글 더미 데이터입니다.',
      image: '',
      username: '아무개',
      createAt: '2021/12/13',
      updateAt: '',
    },
    {
      id: 5,
      makgeolliId: 3,
      userId: 3,
      star: 5,
      comment: '클라이언트 테스트중..',
      image: '',
      username: '홍길동',
      createAt: '2022/01/09',
      updateAt: '',
    },
    {
      id: 6,
      makgeolliId: 18,
      userId: 3,
      star: 4,
      comment: '클라이언트 테스트중... 유저번호 1번 막걸리번호 18번 댓글 6번',
      image: '',
      username: '김철수',
      createAt: '2012/03/09',
      updateAt: '',
    },
    {
      id: 7,
      makgeolliId: 18,
      userId: 2,
      star: 4,
      comment:
        '클라이언트 테스트중... 유저번호 1번 막걸리번호 18번 댓글 7번 입니다@@@@ 내 댓글 테스트중',
      image: '',
      username: '사용자댓글',
      createAt: '2012/03/09',
      updateAt: '',
    },
  ],
};

export default res;
