const res = {
  data: [
    {
      id: 143,
      name: '(주)초가',
      address: '강원도 철원군 김화읍 청양리 2889',
      number: 334587676,
      kinds: '초가우리쌀막걸리',
      makgeolli_id: 18,
      map:
        'https://s3.ap-northeast-2.amazonaws.com/jumo.ml/NewPhoto/%E1%84%8E%E1%85%A9%E1%84%80%E1%85%A1%E1%84%8B%E1%85%AE%E1%84%85%E1%85%B5%E1%84%8A%E1%85%A1%E1%86%AF%E1%84%86%E1%85%A1%E1%86%A8%E1%84%80%E1%85%A5%E1%86%AF%E1%84%85%E1%85%B5.jpg',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 144,
      name: '포천일동주조',
      address: '경기 포천시 일동면 성장로 411',
      number: 315356833,
      kinds: '포천일동막걸리',
      makgeolli_id: 19,
      map:
        'https://s3.ap-northeast-2.amazonaws.com/jumo.ml/NewPhoto/%E1%84%80%E1%85%A1%E1%84%91%E1%85%A7%E1%86%BC%E1%84%8C%E1%85%A1%E1%86%BA%E1%84%86%E1%85%A1%E1%86%A8%E1%84%80%E1%85%A5%E1%86%AF%E1%84%85%E1%85%B5.jpg',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 145,
      name: '이동막걸리공장',
      address: '경기 포천시 이동면 화동로 2466',
      number: 315366365,
      kinds: '이동쌀막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 146,
      name: '진로양조',
      address: '강원 홍천군 홍천읍 솔골길 7',
      number: 334359966,
      kinds: '설악쌀막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 147,
      name: '서울장수진천공장',
      address: '충북 진천군 광혜원면 죽현길 141',
      number: 435377611,
      kinds: '장수생막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 148,
      name: '최행숙전통주가',
      address: '경기 파주시 법원읍 사임당로 763',
      number: 319581297,
      kinds: '파주쌀막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 149,
      name: '(주)우리술',
      address: '경기 가평군 조종면 대보간선로 29 (주)우리술',
      number: 315858525,
      kinds: '가평잣막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 150,
      name: '느린마을양조장양재본점',
      address: '서울 서초구 강남대로27길 7-9 배상면주가',
      number: 25797710,
      kinds: '송이동동주',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 151,
      name: '남한산성양조',
      address: '경기 광주시 도척면 고녹길80번길 18-2',
      number: null,
      kinds: '산삼가득막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 152,
      name: '남한산성소주',
      address: '경기 광주시 곤지암읍 광여로 555-3',
      number: 317691100,
      kinds: '참살이탁주',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 153,
      name: '오성주조장',
      address: '경기 이천시 단월로28번길 3',
      number: 316335864,
      kinds: '이천생막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 154,
      name: '진천덕산양조',
      address: '충북 진천군 덕산읍 초금로 712',
      number: 435353567,
      kinds: '덕산생쌀막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 155,
      name: '천지인주조',
      address: '충남 공주시 의당면 율정길 158-21',
      number: 418545486,
      kinds: '공주알밤주',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 156,
      name: '조은술세종',
      address: '충북 청주시 청원구 사천로18번길 5-2',
      number: 432187688,
      kinds: '세종생막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 157,
      name: '울릉도호박막걸리',
      address: '경상북도 울릉군 울릉읍 약수터길 18',
      number: 547913738,
      kinds: '울릉도호박막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 158,
      name: '운봉주조',
      address: '전북 남원시 운봉읍 황산로 1018',
      number: 636340009,
      kinds: '운봉생막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 159,
      name: '제주샘주',
      address: '제주 제주시 애월읍 애원로 283',
      number: 647994225,
      kinds: '제주오매기술',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 160,
      name: '이화백주',
      address: '경남 양산시 상북면 충렬로 941',
      number: 553755677,
      kinds: '이화백주',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 161,
      name: '배혜정도가',
      address: '경기 화성시 정남면 서봉로 835',
      number: 313549376,
      kinds: '고구마막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 162,
      name: '여수주조공사',
      address: '전남 여수시 좌수영로 361',
      number: 616525744,
      kinds: '여수생막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 163,
      name: '곡성합동주조장',
      address: '전남 곡성군 곡성읍 학교로 118',
      number: null,
      kinds: '곡성생막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 164,
      name: '해창주조장',
      address: '전남 해남군 화산면 해창길 1 해창주조장',
      number: 615325152,
      kinds: '해창막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 165,
      name: '농업회사법인회곡양조장',
      address: '경북 안동시 풍산읍 산업단지5길 39',
      number: 548537777,
      kinds: '안동회곡막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 166,
      name: '생막걸리대전부르스',
      address: '대전 유성구 원촌동 49-2',
      number: 428619310,
      kinds: '대전부르스막걸리',
      createdAt: null,
      updatedAt: null,
    },
    {
      id: 167,
      name: '국순당 화성양조장',
      address: '경기 화성시 봉담읍 매송고색로 452',
      number: 312923190,
      kinds: '국순당',
      createdAt: null,
      updatedAt: null,
    },
  ],
  message: 'ok',
};

export default res;
